<script type="text/javascript" src="<?= base_url('assets/datatables.min.js') ?>"></script>
<script type="text/javascript" src="<?= base_url('assets/js/moment.min.js') ?>"></script>
<script type="text/javascript">
  setTimeout(function(){
    document.getElementById('pesan').style.display = 'none';
  }, 5000);
</script>
<script>
  if ('<?= $this->uri->segment(2) ?>' == 'pc') {
    $(document).ready( function () {
      tampil_data_pc($('#inputBulan').val(),$('#inputTahun').val());

      $('#myTable').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: [
      // {
      //   extend: 'copyHtml5',
      //   text: '<i class="fas fa-copy"></i>',
      //   titleAttr: 'Copy'
      // },
      // {
      //   extend: 'excelHtml5',
      //   text: '<i class="fas fa-file-excel"></i>',
      //   titleAttr: 'Excel'
      // },
      // {
      //   extend: 'csvHtml5',
      //   text: '<i class="fas fa-file-csv"></i>',
      //   titleAttr: 'CSV'
      // },
      // {
      //   extend: 'pdfHtml5',
      //   text: '<i class="fas fa-file-pdf"></i>',
      //   titleAttr: 'PDF'
      // },
        // {
        //   extend: 'pdfHtml5',
        //   text: '<i class="fas fa-check"></i> PDF with image',
        //   customize: function ( doc ) {
        //       // Splice the image in after the header, but before the table
        //       doc.content.splice( 1, 0, {
        //           margin: [ 0, 0, 0, 12 ],
        //           alignment: 'center',
        //           image: '<?= base_url('assets/gambar/logo-ish.png') ?>'
        //       } );
        //       // Data URL generated by http://dataurl.net/#dataurlmaker
        //   }
        // },
        {
          text: '<i class="fas fa-plus"></i> Tambah Data',
          action: function ( e, dt, node, config ) {
            $('.modal-title').text('Tambah Data');
            $('#myForm').attr('action', "<?= site_url('checklist/tambah/pc') ?>");
            $('#input_id_checklist_pc').val('');
            $('#input_pc_id').val('');
            $('#input_nama_petugas').val('');
            $('#input_M1').prop("checked", false);
            $('#input_M2').prop("checked", false);
            $('#input_CPU').prop("checked", false);
            $('#input_TL').val('');
            $('#input_IT').val('');
            $('#input_keterangan').val('');
            $('#myModal').modal('show');
          }
        }
        ]
      } );

      $('#inputBulan').on('change', function() {
        tampil_data_pc(this.value, $('#inputTahun').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_pc($('#inputBulan').val(), this.value);
      });

      function tampil_data_pc(bulan, tahun){
        $.ajax({
          type  : 'ajax',
          url   : '<?php echo site_url()?>/checklist/pc_list/'+bulan+'/'+tahun,
          async : false,
          dataType : 'json',
          success : function(data){
            var html = '';
            var i;
            for(i=0; i<data.length; i++){
              html += '<tr>'+
              '<td class="text-center">'+data[i].pc_id+'</td>'+
              '<td>'+moment(data[i].tanggal).format('DD/MM/YYYY')+'</td>'+
              '<td>'+data[i].nama_petugas+'</td>'+
              '<td class="text-center">'+((data[i].M1 == 'cek')?'&#x2713;':'-')+'</td>'+
              '<td class="text-center">'+((data[i].M2 == 'cek')?'&#x2713;':'-')+'</td>'+
              '<td class="text-center">'+((data[i].CPU == 'cek')?'&#x2713;':'-')+'</td>'+
              '<td>'+data[i].TL+'</td>'+
              '<td>'+data[i].IT+'</td>'+
              '<td>'+data[i].keterangan+'</td>'+
              '<td><button id="btnEdit" class="btn btn-warning" value="'+data[i].id_checklist_pc+'">Edit</button> <button id="btnHapus" class="btn btn-danger" value="'+data[i].id_checklist_pc+'">Hapus</button></td>'+
              '</tr>';
            }
            $('#show_data').html(html);

            $('#btnHapus').click(function(){
              alert("ID untuk Hapus = "+this.value);
            // $('#myModal').modal('show');
          });
          }
        });
      }

      $('#show_data').on('click','#btnEdit',function(){
      // alert($('#inputBulan').val());
      $.ajax({
        type     : 'GET',
        url      : '<?php echo site_url()?>/checklist/pc_list/nope/nope/'+this.value,
        dataType : 'json',
        success : function(data){
          $('#input_id_checklist_pc').val(data[0].id_checklist_pc);
          $('#input_pc_id').val(data[0].pc_id);
          $('#input_nama_petugas').val(data[0].nama_petugas);
          $('#input_M1').prop("checked", ((data[0].M1 == 'cek')?true:false));
          $('#input_M2').prop("checked", ((data[0].M2 == 'cek')?true:false));
          $('#input_CPU').prop("checked", ((data[0].CPU == 'cek')?true:false));
          $('#input_TL').val(data[0].TL);
          $('#input_IT').val(data[0].IT);
          $('#input_keterangan').val(data[0].keterangan);
        }
      });
      $('.modal-title').text('Edit Data');
      $('#myForm').attr('action', "<?= site_url('checklist/edit/pc') ?>");
      // alert("ID = "+this.value);
      $('#myModal').modal('show');
    });

      $('#show_data').on('click','#btnHapus',function(){
        window.location.href = "<?= site_url('checklist/hapus/pc/') ?>"+this.value;
        return false;
      });
    } );
  } else if ('<?= $this->uri->segment(2) ?>' == 'ac') {
    $(document).ready( function () {
      tampil_data_ac($('#inputBulan').val(), $('#inputTahun').val());

      $('#myTable').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: [{
          text: '<i class="fas fa-plus"></i> Tambah Data',
          action: function ( e, dt, node, config ) {
            $('.modal-title').text('Tambah Data');
            $('#myForm').attr('action', "<?= site_url('checklist/tambah/ac') ?>");
            $('#input_id_checklist_ac').val('');
            $('#input_ruangan').val('');
            $('#input_sts_ac_pagi').val('');
            $('#input_temp_pagi').val('');
            $('#input_pic_pagi').val('');
            $('#input_keterangan_pagi').val('');
            $('#input_sts_ac_malam').val('');
            $('#input_temp_malam').val('');
            $('#input_pic_malam').val('');
            $('#input_keterangan_malam').val('');
            $('#myModal').modal('show');
          }
        }]
      } );

      $('#inputBulan').on('change', function() {
        tampil_data_ac(this.value, $('#inputTahun').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_ac($('#inputBulan').val(), this.value);
      });

      function tampil_data_ac(bulan, tahun){
        $.ajax({
          type  : 'ajax',
          url   : '<?php echo site_url()?>/checklist/ac_list/'+bulan+'/'+tahun,
          async : false,
          dataType : 'json',
          success : function(data){
            var html = '';
            var i;
            for(i=0; i<data.length; i++){
              html += '<tr>'+
              '<td>'+moment(data[i].tanggal).format('DD/MM/YYYY')+'</td>'+
              '<td>'+data[i].sts_ac_pagi+'</td>'+
              '<td>'+data[i].temp_pagi+'</td>'+
              '<td>'+data[i].pic_pagi+'</td>'+
              '<td>'+data[i].keterangan_pagi+'</td>'+
              '<td>'+data[i].sts_ac_malam+'</td>'+
              '<td>'+data[i].temp_malam+'</td>'+
              '<td>'+data[i].pic_malam+'</td>'+
              '<td>'+data[i].keterangan_malam+'</td>'+
              '<td><button id="btnEdit" class="btn btn-warning" value="'+data[i].id_checklist_ac+'">Edit</button> <button id="btnHapus" class="btn btn-danger" value="'+data[i].id_checklist_ac+'">Hapus</button></td>'+
              '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }

      $('#show_data').on('click','#btnEdit',function(){
        $.ajax({
          type     : 'GET',
          url      : '<?php echo site_url()?>/checklist/ac_list/nope/nope/'+this.value,
          dataType : 'json',
          success : function(data){
            $('#input_id_checklist_ac').val(data[0].id_checklist_ac);
            $('#input_ruangan').val(data[0].ruangan);
            $('#input_sts_ac_pagi').val(data[0].sts_ac_pagi);
            $('#input_temp_pagi').val(data[0].temp_pagi);
            $('#input_pic_pagi').val(data[0].pic_pagi);
            $('#input_keterangan_pagi').val(data[0].keterangan_pagi);
            $('#input_sts_ac_malam').val(data[0].sts_ac_malam);
            $('#input_temp_malam').val(data[0].temp_malam);
            $('#input_pic_malam').val(data[0].pic_malam);
            $('#input_keterangan_malam').val(data[0].keterangan_malam);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('action', "<?= site_url('checklist/edit/ac') ?>");
        $('#myModal').modal('show');
      });

      $('#show_data').on('click','#btnHapus',function(){
        window.location.href = "<?= site_url('checklist/hapus/ac/') ?>"+this.value;
        return false;
      });
    } );
  } else if ('<?= $this->uri->segment(2) ?>' == 'ups') {
    $(document).ready( function () {
      tampil_data_ups($('#inputBulan').val(), $('#inputTahun').val());

      $('#myTable').DataTable( {
        responsive: true,
        dom: 'Bfrtip',
        buttons: [{
          text: '<i class="fas fa-plus"></i> Tambah Data',
          upstion: function ( e, dt, node, config ) {
            $('.modal-title').text('Tambah Data');
            $('#myForm').attr('upstion', "<?= site_url('checklist/tambah/ups') ?>");
            $('#input_id_checklist_ups').val('');
            $('#input_ruangan').val('');
            $('#input_sts_ups_pagi').val('');
            $('#input_temp_pagi').val('');
            $('#input_pic_pagi').val('');
            $('#input_keterangan_pagi').val('');
            $('#input_sts_ups_malam').val('');
            $('#input_temp_malam').val('');
            $('#input_pic_malam').val('');
            $('#input_keterangan_malam').val('');
            $('#myModal').modal('show');
          }
        }]
      } );

      $('#inputBulan').on('change', function() {
        tampil_data_ups(this.value, $('#inputTahun').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_ups($('#inputBulan').val(), this.value);
      });

      function tampil_data_ups(bulan, tahun){
        $.ajax({
          type  : 'ajax',
          url   : '<?php echo site_url()?>/checklist/ups_list/'+bulan+'/'+tahun,
          async : false,
          dataType : 'json',
          success : function(data){
            var html = '';
            var i;
            for(i=0; i<data.length; i++){
              html += '<tr>'+
              '<td>'+moment(data[i].tanggal).format('DD/MM/YYYY')+'</td>'+
              '<td>'+data[i].sts_ups_pagi+'</td>'+
              '<td>'+data[i].temp_pagi+'</td>'+
              '<td>'+data[i].pic_pagi+'</td>'+
              '<td>'+data[i].keterangan_pagi+'</td>'+
              '<td>'+data[i].sts_ups_malam+'</td>'+
              '<td>'+data[i].temp_malam+'</td>'+
              '<td>'+data[i].pic_malam+'</td>'+
              '<td>'+data[i].keterangan_malam+'</td>'+
              '<td><button id="btnEdit" class="btn btn-warning" value="'+data[i].id_checklist_ups+'">Edit</button> <button id="btnHapus" class="btn btn-danger" value="'+data[i].id_checklist_ups+'">Hapus</button></td>'+
              '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }

      $('#show_data').on('click','#btnEdit',function(){
        $.ajax({
          type     : 'GET',
          url      : '<?php echo site_url()?>/checklist/ups_list/nope/nope/'+this.value,
          dataType : 'json',
          success : function(data){
            $('#input_id_checklist_ups').val(data[0].id_checklist_ups);
            $('#input_ruangan').val(data[0].ruangan);
            $('#input_sts_ups_pagi').val(data[0].sts_ups_pagi);
            $('#input_temp_pagi').val(data[0].temp_pagi);
            $('#input_pic_pagi').val(data[0].pic_pagi);
            $('#input_keterangan_pagi').val(data[0].keterangan_pagi);
            $('#input_sts_ups_malam').val(data[0].sts_ups_malam);
            $('#input_temp_malam').val(data[0].temp_malam);
            $('#input_pic_malam').val(data[0].pic_malam);
            $('#input_keterangan_malam').val(data[0].keterangan_malam);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('upstion', "<?= site_url('checklist/edit/ups') ?>");
        $('#myModal').modal('show');
      });

      $('#show_data').on('click','#btnHapus',function(){
        window.location.href = "<?= site_url('checklist/hapus/ups/') ?>"+this.value;
        return false;
      });
    } );
  }
</script>