<script type="text/javascript" src="<?= base_url('assets/jquery-3.6.1.min.js') ?>"></script>
<script type="text/javascript" src="<?= base_url('assets/datatables.min.js') ?>"></script>
<script type="text/javascript" src="<?= base_url('assets/js/moment.min.js') ?>"></script>
<script type="text/javascript">
  setTimeout(function() {
    document.getElementById('pesan').style.display = 'none';
  }, 5000);
</script>
<script>
  if ('<?= $this->uri->segment(2) ?>' == 'pc') {
    $(document).ready(function() {
      tampil_data_pc($('#inputBulan').val(), $('#inputTahun').val(), $('input[name=shiftForm]:checked').val());

      $('#myTable').DataTable({
        responsive: true,
        dom: 'Bfrtip',
        buttons: [
          // {
          //   extend: 'copyHtml5',
          //   text: '<i class="fas fa-copy"></i>',
          //   titleAttr: 'Copy'
          // },
          // {
          //   extend: 'excelHtml5',
          //   text: '<i class="fas fa-file-excel"></i>',
          //   titleAttr: 'Excel'
          // },
          // {
          //   extend: 'csvHtml5',
          //   text: '<i class="fas fa-file-csv"></i>',
          //   titleAttr: 'CSV'
          // },
          // {
          //   extend: 'pdfHtml5',
          //   text: '<i class="fas fa-file-pdf"></i>',
          //   titleAttr: 'PDF'
          // },
          // {
          //   extend: 'pdfHtml5',
          //   text: '<i class="fas fa-check"></i> PDF with image',
          //   customize: function ( doc ) {
          //       // Splice the image in after the header, but before the table
          //       doc.content.splice( 1, 0, {
          //           margin: [ 0, 0, 0, 12 ],
          //           alignment: 'center',
          //           image: '<?= base_url('assets/gambar/logo-ish.png') ?>'
          //       } );
          //       // Data URL generated by http://dataurl.net/#dataurlmaker
          //   }
          // },
          {
            text: '<i class="fas fa-plus"></i> Tambah Data',
            action: function(e, dt, node, config) {
              $('.modal-title').text('Tambah Data');
              $('#myForm').attr('action', "<?= site_url('ChecklistME/tambah/pc') ?>");
              $('#input_tanggal').val('<?= date('d-m-Y') ?>');
              $('#input_id_checklist_pc').val('');
              $('#input_pc_id').val('');
              $('#input_nama_petugas').val('');
              $('#input_M1').prop("checked", false);
              $('#input_M2').prop("checked", false);
              $('#input_CPU').prop("checked", false);
              $('#input_TL').val('');
              $('#input_IT').val('');
              $('#input_keterangan').val('');
              $('#myModal').modal('show');
            }
          }
        ]
      });

      $('#inputBulan').on('change', function() {
        tampil_data_pc(this.value, $('#inputTahun').val(), $('input[name=shiftForm]:checked').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_pc($('#inputBulan').val(), this.value, $('input[name=shiftForm]:checked').val());
      });

      $('#inputShiftForm input[type=radio]').change(function() {
        tampil_data_pc($('#inputBulan').val(), $('#inputTahun').val(), this.value);
      });

      function tampil_data_pc(bulan, tahun, shift) {
        $.ajax({
          type: 'ajax',
          url: '<?php echo site_url() ?>/ChecklistME/pc_list/' + bulan + '/' + tahun + '/' + shift,
           method: 'GET',
          async: false,
          dataType: 'JSON',
          success: function(data) {
            var html = '';
            var i;
            var gambar;
            for (i = 0; i < data.length; i++) {
              if (data[i].gambar == null) {
                gambar = 'default.jpg';
              } else {
                gambar = data[i].gambar;
              }
              html += '<tr>' +
                '<td class="text-center">' + data[i].pc_id + '</td>' +
                '<td>' + moment(data[i].tanggal).format('DD/MM/YYYY') + '</td>' +
                '<td>' + data[i].nama_petugas + '</td>' +
                '<td class="text-center">' + ((data[i].M1 == 'cek') ? '&#x2713;' : '-') + '</td>' +
                '<td class="text-center">' + ((data[i].M2 == 'cek') ? '&#x2713;' : '-') + '</td>' +
                '<td class="text-center">' + ((data[i].CPU == 'cek') ? '&#x2713;' : '-') + '</td>' +
                '<td>' + data[i].jumlah + '</td>' +
                '<td>' + data[i].TL + '</td>' +
                '<td><center><img src="<?= base_url() ?>uploads/Paraf/' + ((data[i].paraf_tl != null) ? data[i].paraf_tl : 'default') + '.png" width="150px" height="150px"></img></center></td>' +
                '<td>' + data[i].IT + '</td>' +
                '<td><center><img src="<?= base_url() ?>uploads/Paraf/' + ((data[i].paraf_it != null) ? data[i].paraf_it : 'default') + '.png" width="150px" height="150px"></img></center></td>' +
                '<td>' + data[i].keterangan + '</td>' +
                '<td><center><img src="<?= base_url() ?>uploads/PC/' + gambar + '" width="150px" height="150px"></img></center></td>' +
                '<td>' + data[i].status + '</td>' +
                // '<td><button id="btnApproveTL" class="btn btn-warning" value="' + data[i].id_checklist_pc + '">Approve TL</button> <a href="<?= base_url() ?>uploads/PC/' + data[i].gambar + '" class = "btn btn-primary"> Lihat Gambar </a></td > ' +
                '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }


      $('#show_data').on('click', '#btnEdit', function() {
        // alert($('#inputBulan').val());
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistME/pc_list/nope/nope/nope/' + this.value,
          dataType: 'json',
          success: function(data) {
            $('#input_tanggal').val(moment(data[0].tanggal).format('DD/MM/YYYY'));
            $("input[name='shift'][value='" + data[0].shift + "']").prop('checked', true);
            $('#input_id_checklist_pc').val(data[0].id_checklist_pc);
            $('#input_pc_id').val(data[0].pc_id);
            $('#input_nama_petugas').val(data[0].nama_petugas);
            $('#jumlah').val(data[0].jumlah);
            $('#input_M1').prop("checked", ((data[0].M1 == 'cek') ? true : false));
            $('#input_M2').prop("checked", ((data[0].M2 == 'cek') ? true : false));
            $('#input_CPU').prop("checked", ((data[0].CPU == 'cek') ? true : false));
            $('#input_TL').val(data[0].TL);
            $('#input_IT').val(data[0].IT);
            $('#input_keterangan').val(data[0].keterangan);
            $('#status').val(data[0].status);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('action', "<?= site_url('ChecklistME/edit/pc') ?>");
        // alert("ID = "+this.value);
        $('#myModal').modal('show');
      });

      $('#show_data').on('click', '#btnHapus', function() {
        if (confirm("Yakin akan menghapus data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistME/hapus/pc/') ?>" + this.value;
        }
      });

      $('#show_data').on('click', '#btnApproveTL', function() {
        if (confirm("Yakin akan Approve data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistME/editApproveTL/pc/') ?>" + this.value;
        }
      });
    });
  } else if ('<?= $this->uri->segment(2) ?>' == 'ac') {
    $(document).ready(function() {
      tampil_data_ac($('#inputBulan').val(), $('#inputTahun').val(), $('#inputRuangan').val());

      // $('#myTable').DataTable({
      //   responsive: true,
      //   dom: 'Bfrtip',
      //   buttons: [{
      //     text: '<i class="fas fa-plus"></i> Tambah Data',
      //     action: function(e, dt, node, config) {
      //       $('.modal-title').text('Tambah Data');
      //       $('#myForm').attr('action', "<?= site_url('ChecklistME/tambah/ac') ?>");
      //       $('#input_id_checklist_ac').val('');
      //       $('#input_ruangan').val('');
      //       $('#input_sts_ac_pagi').val('');
      //       $('#input_temp_pagi').val('');
      //       $('#input_pic_pagi').val('');
      //       $('#input_keterangan_pagi').val('');
      //       $('#input_sts_ac_malam').val('');
      //       $('#input_temp_malam').val('');
      //       $('#input_pic_malam').val('');
      //       $('#input_keterangan_malam').val('');
      //       $('#myModal').modal('show');
      //     }
      //   }]
      // });

      $('#inputBulan').on('change', function() {
        tampil_data_ac(this.value, $('#inputTahun').val(), $('#inputRuangan').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_ac($('#inputBulan').val(), this.value, $('#inputRuangan').val());
      });

      $('#inputRuangan').on('change', function() {
        tampil_data_ac($('#inputBulan').val(), $('#inputTahun').val(), this.value);
      });

      function tampil_data_ac(bulan, tahun, idRuangan) {
        $.ajax({
          type: 'ajax',
          url: '<?php echo site_url() ?>/ChecklistME/ac_list/' + bulan + '/' + tahun + '/' + idRuangan,
           method: 'GET',
          async: false,
          dataType: 'JSON',
          success: function(data) {
            var html = '';
            var i;
            for (i = 0; i < data.length; i++) {
              html += '<tr>' +
                '<td>' + moment(data[i].tanggal).format('DD/MM/YYYY') + '</td>' +
                '<td class="text-center">' + data[i].sts_ac_pagi + '</td>' +
                '<td class="text-center">' + data[i].temp_pagi + '</td>' +
                '<td>' + data[i].pic_pagi + '</td>' +
                '<td>' + data[i].keterangan_pagi + '</td>' +
                '<td class="text-center">' + data[i].sts_ac_malam + '</td>' +
                '<td class="text-center">' + data[i].temp_malam + '</td>' +
                '<td>' + data[i].pic_malam + '</td>' +
                '<td>' + data[i].keterangan_malam + '</td>' +
                '<td><button id="btnEdit" class="btn btn-warning" value="' + data[i].id_checklist_ac + '">Edit</button> <button id="btnHapus" class="btn btn-danger" value="' + data[i].id_checklist_ac + '">Hapus</button></td>' +
                '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }

      $('#show_data').on('click', '#btnEdit', function() {
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistME/ac_list/nope/nope/nope/' + this.value,
          dataType: 'json',
          success: function(data) {
            $('#input_id_checklist_ac').val(data[0].id_checklist_ac);
            $('#input_ruangan').val(data[0].id_ruangan);
            $('#input_sts_ac_pagi').val(data[0].sts_ac_pagi);
            $('#input_temp_pagi').val(data[0].temp_pagi);
            $('#input_pic_pagi').val(data[0].pic_pagi);
            $('#input_keterangan_pagi').val(data[0].keterangan_pagi);
            $('#input_sts_ac_malam').val(data[0].sts_ac_malam);
            $('#input_temp_malam').val(data[0].temp_malam);
            $('#input_pic_malam').val(data[0].pic_malam);
            $('#input_keterangan_malam').val(data[0].keterangan_malam);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('action', "<?= site_url('ChecklistME/edit/ac') ?>");
        $('#myModal').modal('show');
      });

      $('#show_data').on('click', '#btnHapus', function() {
        if (confirm("Yakin akan menghapus data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistME/hapus/ac/') ?>" + this.value;
        }
      });
    });
  } else if ('<?= $this->uri->segment(2) ?>' == 'ups') {
    $(document).ready(function() {
      tampil_data_ups($('#inputBulan').val(), $('#inputTahun').val());

      // $('#myTable').DataTable({
      //   responsive: true,
      //   dom: 'Bfrtip',
      //   buttons: [{
      //     text: '<i class="fas fa-plus"></i> Tambah Data',
      //     action: function(e, dt, node, config) {
      //       $('.modal-title').text('Tambah Data');
      //       $('#myForm').attr('action', "<?= site_url('ChecklistME/tambah/ups') ?>");
      //       $('#input_id_checklist_ups').val('');
      //       $('#input_lokasi').val('');
      //       $('#input_merk').val('');
      //       $('#input_type').val('');
      //       $('#input_input').val('');
      //       $('#input_output').val('');
      //       $('#input_baterai_time').val('');
      //       $('#input_petugas').val('');
      //       $('#input_keterangan').val('');
      //       $('#myModal').modal('show');
      //     }
      //   }]
      // });

      $('#inputBulan').on('change', function() {
        tampil_data_ups(this.value, $('#inputTahun').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_ups($('#inputBulan').val(), this.value);
      });

      function tampil_data_ups(bulan, tahun) {
        $.ajax({
          type: 'ajax',
          url: '<?php echo site_url() ?>/ChecklistME/ups_list/' + bulan + '/' + tahun,
           method: 'GET',
          async: false,
          dataType: 'JSON',
          success: function(data) {
            var html = '';
            var i;
            for (i = 0; i < data.length; i++) {
              html += '<tr>' +
                '<td class="text-center">' + moment(data[i].tanggal).format('DD/MM/YYYY') + '</td>' +
                '<td>' + data[i].lokasi + '</td>' +
                '<td>' + data[i].merk + '</td>' +
                '<td>' + data[i].type + '</td>' +
                '<td class="text-center">' + data[i].input + '</td>' +
                '<td class="text-center">' + data[i].output + '</td>' +
                '<td class="text-center">' + data[i].baterai_time + '</td>' +
                '<td>' + data[i].petugas + '</td>' +
                '<td>' + data[i].keterangan + '</td>' +
                '<td><button id="btnEdit" class="btn btn-warning" value="' + data[i].id_checklist_ups + '">Edit</button> <button id="btnHapus" class="btn btn-danger" value="' + data[i].id_checklist_ups + '">Hapus</button></td>' +
                '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }

      $('#show_data').on('click', '#btnEdit', function() {
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistME/ups_list/nope/nope/' + this.value,
          dataType: 'json',
          success: function(data) {
            $('#input_id_checklist_ups').val(data[0].id_checklist_ups);
            $('#input_lokasi').val(data[0].lokasi);
            $('#input_merk').val(data[0].merk);
            $('#input_type').val(data[0].type);
            $('#input_input').val(data[0].input);
            $('#input_output').val(data[0].output);
            $('#input_baterai_time').val(data[0].baterai_time);
            $('#input_petugas').val(data[0].petugas);
            $('#input_keterangan').val(data[0].keterangan);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('action', "<?= site_url('ChecklistME/edit/ups') ?>");
        $('#myModal').modal('show');
      });

      $('#show_data').on('click', '#btnHapus', function() {
        // return false;
        // var choice = confirm($(this).attr('data-confirm'));

        if (confirm("Yakin akan menghapus data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistME/hapus/ups/') ?>" + this.value;
        }
      });
    });
  } else if ('<?= $this->uri->segment(2) ?>' == 'cctv') {
    $(document).ready(function() {
      tampil_data_cctv($('#inputBulan').val(), $('#inputTahun').val(), $('#inputShift').val());

      let table = $('#myTable').DataTable({
        responsive: true,
        autoWidth: false,
        dom: 'Bfrtip',
        buttons: [{
          text: '<i class="fas fa-plus"></i> Tambah Checklist',
          action: function(e, dt, node, config) {
            $('#formInsert').attr('hidden', false);
            $('#formEditKeterangan').attr('hidden', true);
            $('.modal-title').text('Tambah Checklist');
            $('#myForm').attr('action', "<?= site_url('ChecklistME/tambah/cctv') ?>");
            $('.formInsertCheck').attr('hidden', false);
            $('.formEditCheck').attr('hidden', true);
            $('#input_id_check_cctv').val('');
            $('#input_tanggal').val('<?= date('d-m-Y') ?>');
            $('#input_id_ruangan').val('');
            $('#input_shift').val($('#inputShift').val());
            $('#myModal').modal('show');
          }
        }]
      });
       
      window.onresize = function() {
          table.columns.adjust().responsive.recalc();
      }  

      $('#inputBulan').on('change', function() {
        tampil_data_cctv(this.value, $('#inputTahun').val(), $('#inputShift').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_cctv($('#inputBulan').val(), this.value, $('#inputShift').val());
      });

      $('#inputShift').on('change', function() {
        tampil_data_cctv($('#inputBulan').val(), $('#inputTahun').val(), this.value);
      });

      function tampil_data_cctv(bulan, tahun, shift) {
        $.ajax({
          type: 'ajax',
          url: '<?php echo site_url() ?>/ChecklistME/cctv_list/' + bulan + '/' + tahun + '/' + shift,
           method: 'GET',
          async: false,
          dataType: 'JSON',
          success: function(data) {
            // alert(data['data2'][0][0].tanggal);
            var html = '';
            var i;
            for (i = 0; i < data.length; i++) {
              html += '<tr>' +
                '<td class="text-center">' + data[i].lantai + '</td>' +
                '<td>' + data[i].nama_ruangan + '</td>';
              for (var j = 1; j <= 31; j++) {
                var tgl = '';
                if (j < 10) {
                  tgl = '0' + j;
                } else {
                  tgl = j;
                }
                var kondisi = eval('data[i].tgl' + tgl);
                html += '<td class="text-center">' + ((kondisi != '') ? ((kondisi == 'baik') ? '&#x2713;' : 'x') : ' ') + '</td>';
              }
              html += '<td>' + data[i].keterangan + '</td>' +
                '<td><button id="btnEdit" class="btn btn-warning" value="' + data[i].id_check_cctv + '">Edit</button></td>' +
                '</tr>';
            }
            $('#show_data').html(html);
          }
        });
      }

      $('#show_data').on('click', '#btnEdit', function() {
        $('.modal-title').text('Edit Data');
        $('#input_id_check_cctv').val(this.value);
        $('#pilihModal').modal('show');
      });

      $('#show_data').on('click', '#btnHapus', function() {
        if (confirm("Yakin akan menghapus data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistME/hapus/cctv/') ?>" + this.value;
        }
      });

      $('#btnEditCheck').click(function() {
        $('#formInsert').attr('hidden', false);
        $('#formEditKeterangan').attr('hidden', true);
        $('#id_check_cctv').attr('hidden', false);
        $('.formInsertCheck').attr('hidden', true);
        $('.formEditCheck').attr('hidden', false);
        $('#myForm').attr('action', "<?= site_url('ChecklistME/edit/cctv') ?>");
        $("input[name='kondisi']").prop('checked', false);
        $('#myModal').modal('show');
        $('#pilihModal').modal('hide');
      });

      $('#input_tanggalEdit').on('change input', function() {
        var tgl = '';
        if (this.value < 10) {
          tgl = '0' + this.value;
        } else {
          tgl = this.value;
        }
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistME/cctv_list/nope/nope/nope/' + ($('#input_id_check_cctv').val()),
          dataType: 'json',
          success: function(data) {
            var kondisi = eval('data[0].tgl' + tgl);
            if (kondisi != '') {
              $("input[name='kondisi'][value='" + kondisi + "']").prop('checked', true);
            } else {
              $("input[name='kondisi']").prop('checked', false);
            }
          }
        });
      });

      $('#btnEditKeterangan').click(function() {
        $('.modal-title').text('Edit Checklist');
        $('#myForm').attr('action', "<?= site_url('ChecklistME/edit/cctv') ?>");
        $('#formInsert').attr('hidden', true);
        $('#formEditKeterangan').attr('hidden', false);
        $('#input_tanggalEdit').val('');
        $('#myModal').modal('show');
        $('#pilihModal').modal('hide');
      });
    });
  } else if ('<?= $this->uri->segment(2) ?>' == 'kebersihan') {
    $(document).ready(function() {
      // console.log($('#inputJam').val());
      tampil_data_kebersihan($('#inputBulan').val(), $('#inputTahun').val(), $('#inputJam').val());
      $('#myTable').css( 'display', 'table' );
      let table = $('#myTable').DataTable({
        responsive: true,
        autoWidth: false,
        dom: 'Bfrtip',
        buttons: [{
          text: '<i class="fas fa-plus"></i> Tambah Checklist',
          action: function(e, dt, node, config) {
            $('#formInsert').attr('hidden', false);
            $('#formEditKeterangan').attr('hidden', true);
            $('.modal-title').text('Tambah Checklist');
            $('#myForm').attr('action', "<?= site_url('ChecklistOB/tambah/kebersihan') ?>");
            $('.formInsertCheck').attr('hidden', false);
            $('.formEditCheck').attr('hidden', true);
            $('#input_id_check_kebersihan').val('');
            // $('#pic').val('');
            $('#input_tanggal').val("<?=date('Y-m-d')?>");
            $('#input_lantai_operasional').val('');
            $('#input_id_ruangan').val('');
            $('#input_jam').val($('#inputJam').val());
            $('#dinding').val('');
            $('#list').val('');
            $('#kaca').val('');
            $('#plafon').val('');
            $('#furniture').val('');
            $('#ws').val('');
            $('#pc').val('');
            $('#ac').val('');
            $('#telephone').val('');
            $('#aksesoris').val('');
            $('#kap_lampu').val('');
            $('#tempat_sampah').val('');
            $('#kursi_staff').val('');
            $('#meja_staff').val('');
            $('#insfected').val('');
            $('#tl_spv').val('');
            $('#nama_user').val('');
            $('#input_keterangan').val('');
            $('#myModal').modal('show');
          }
        }]
      });
      
      window.onresize = function() {
          table.columns.adjust().responsive.recalc();
      }  

      $('#inputBulan').on('change', function() {
        tampil_data_kebersihan(this.value, $('#inputTahun').val(), $('#inputJam').val());
      });

      $('#inputTahun').on('change', function() {
        tampil_data_kebersihan($('#inputBulan').val(), this.value, $('#inputJam').val());
      });

      $('#inputJam').on('change', function() {
        tampil_data_kebersihan($('#inputBulan').val(), $('#inputTahun').val(), this.value);
      });

      function tampil_data_kebersihan(bulan, tahun, shift) {
        $.ajax({
          type: 'ajax',
          url: '<?php echo site_url() ?>/ChecklistOB/kebersihan_list/' + bulan + '/' + tahun + '/' + shift,
          method: 'GET',
          async: false,
          dataType: 'JSON',
          success: function(data) {
            // alert(data['data2'][0][0].tanggal);
              let html = '';
              if(data.length != 0){
              for (i = 0; i < data.length; i++) {
                console.log(data[i].tanggal);
              html += `<tr>
                <td class="text-center">${data[i].tanggal}</td>
                <td class="text-center">${data[i].jam}</td>
                <td class="text-center">${data[i].lantai_operasional}</td>
                <td class="text-center">${data[i].nama_ruangan}</td>
                <td class="text-center">${data[i].pic}</td>
                <td class="text-center">${data[i].lantai}</td>
                <td class="text-center">${data[i].dinding}</td>
                <td class="text-center">${data[i].list}</td>
                <td class="text-center">${data[i].kaca}</td>
                <td class="text-center">${data[i].plafon}</td>
                <td class="text-center">${data[i].furniture}</td>
                <td class="text-center">${data[i].ws}</td>
                <td class="text-center">${data[i].pc}</td>
                <td class="text-center">${data[i].ac}</td>
                <td class="text-center">${data[i].telephone}</td>
                <td class="text-center">${data[i].aksesoris}</td>
                <td class="text-center">${data[i].kap_lampu}</td>
                <td class="text-center">${data[i].tempat_sampah}</td>
                <td class="text-center">${data[i].kursi_staff}</td>
                <td class="text-center">${data[i].meja_staff}</td>
                <td class="text-center">${data[i].insfected}</td>
                <td class="text-center">${data[i].tl_spv}</td>
                <td class="text-center">${data[i].nama_user}</td>`;
                html += '<td bgcolor="white"><center><img src="<?= base_url() ?>uploads/Paraf/' + ((data[i].paraf_it != null) ? data[i].paraf_it : 'default') + '.png" width="150px" height="150px"></img></center></td>';
              
              html += `<td>${data.keterangan}</td>
                <td>
                  <button id="btnEdit" class="btn btn-warning" value="${data[i].id_check_kebersihan}">Edit</button>
                  <button id="btnHapus" class="btn btn-danger" value="${data[i].id_check_kebersihan}">Hapus</button> 
                </td>
                </tr>`;
              }
            }
            $('#show_data').html(html);
          }
        });
      }

      // $('#show_data').on('click', '#btnEdit', function() {
      //   $('.modal-title').text('Edit Data');
      //   $('#input_id_check_kebersihan').val(this.value);
      //   $('#pilihModal').modal('show');
      // });

      $('#show_data').on('click', '#btnHapus', function() {
        if (confirm("Yakin akan menghapus data yang dipilih?")) {
          window.location.href = "<?= site_url('ChecklistOB/hapus/kebersihan/') ?>" + this.value;
        }
      });

      $('#show_data').on('click', '#btnEdit', function() {
        // alert($('#inputBulan').val());
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistOB/kebersihan_list/nope/nope/nope/' + this.value,
          dataType: 'json',
          success: function(data) {
            $('#input_id_check_kebersihan').val(data[0].id_check_kebersihan);
            $('#input_tanggal').val(data[0].tanggal);
            // $("input[name='shift'][value='" + data[0].shift + "']").prop('checked', true);
            $('#pic').val(data[0].pic);
            $('#input_lantai_operasional').val(data[0].lantai_operasional);
            $('#input_id_ruangan').val(data[0].id_ruangan);
            $('#input_jam').val(data[0].jam);
            $('#input_lantai').val(data[0].lantai);
            $('#input_dinding').val(data[0].dinding);
            $('#input_list').val(data[0].list);
            $('#input_kaca').val(data[0].kaca);
            $('#input_plafon').val(data[0].plafon);
            $('#input_furniture').val(data[0].furniture);
            $('#input_ws').val(data[0].ws);
            $('#input_pc').val(data[0].pc);
            $('#input_ac').val(data[0].ac);
            $('#input_telephone').val(data[0].telephone);
            $('#input_aksesoris').val(data[0].aksesoris);
            $('#input_kap_lampu').val(data[0].kap_lampu);
            $('#input_tempat_sampah').val(data[0].tempat_sampah);
            $('#input_kursi_staff').val(data[0].kursi_staff);
            $('#input_meja_staff').val(data[0].meja_staff);
            $('#input_insfected').val(data[0].insfected);
            $('#input_tl_spv').val(data[0].tl_spv);
            $('#input_nama_user').val(data[0].nama_user);
            $('#input_keterangan').val(data[0].keterangan);
            // $('#input_status').val(data[0].status);
          }
        });
        $('.modal-title').text('Edit Data');
        $('#myForm').attr('action', "<?= site_url('ChecklistOB/edit/kebersihan') ?>");
        // alert("ID = "+this.value);
        $('#myModal').modal('show');
      });

      $('#input_tanggalEdit').on('change input', function() {
        var tgl = '';
        if (this.value < 10) {
          tgl = '0' + this.value;
        } else {
          tgl = this.value;
        }
        $.ajax({
          type: 'GET',
          url: '<?php echo site_url() ?>/ChecklistOB/kebersihan_list/nope/nope/nope/' + ($('#input_id_check_kebersihan').val()),
          dataType: 'json',
          success: function(data) {
            var kondisi = eval('data[0].tgl' + tgl);
            if (kondisi != '') {
              $("input[name='kondisi'][value='" + kondisi + "']").prop('checked', true);
            } else {
              $("input[name='kondisi']").prop('checked', false);
            }
          }
        });
      });

      // $('#btnEditKeterangan').click(function() {
      //   $('.modal-title').text('Edit Checklist');
      //   $('#myForm').attr('action', "<?= site_url('ChecklistOB/edit/kebersihan') ?>");
      //   $('#formInsert').attr('hidden', true);
      //   $('#formEditKeterangan').attr('hidden', false);
      //   $('#input_tanggalEdit').val('');
      //   $('#myModal').modal('show');
      //   $('#pilihModal').modal('hide');
      // });
    });
  }
</script>